# Generated by Django 5.2 on 2025-04-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
