# Generated by Django 5.2 on 2025-04-20 07:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='orderplacedfinal',
        ),
        migrations.AlterModelTable(
            name='orderplacedfinal',
            table='order_placed_final',
        ),
    ]
