# Generated by Django 5.2 on 2025-04-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_rename_cart_orderplacedfinal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplacedfinal',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderplacedfinal',
            name='user',
        ),
        migrations.AddField(
            model_name='orderplacedfinal',
            name='product_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderplacedfinal',
            name='user_username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderplacedfinal',
            name='user_other_details',
            field=models.CharField(max_length=255),
        ),
    ]
