# Generated by Django 5.2 on 2025-04-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_orderplacedfinal_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplacedfinal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
