# Generated by Django 5.2 on 2025-04-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_orderplacedfinal_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplacedfinal',
            old_name='price',
            new_name='Price',
        ),
    ]
