# Generated by Django 5.2 on 2025-04-20 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_rename_price_orderplacedfinal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetails',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
