# Generated by Django 5.2 on 2025-04-20 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_carddetails_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
