# Generated by Django 5.2 on 2025-04-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_sellerprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sellerprofile',
            table='SellerProfile',
        ),
    ]
