# Generated by Django 5.2 on 2025-04-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_alter_productsofthisweb_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='unit_of_measurement',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('qt', 'Quintal (qt)'), ('ton', 'Metric Ton (ton)'), ('lbs', 'Pounds (lbs)'), ('none', 'None'), ('oz', 'Ounce (oz)'), ('l', 'Liter (L)'), ('ml', 'Milliliter (ml)'), ('gal', 'Gallon (gal)'), ('pt', 'Pint (pt)'), ('fl_oz', 'Fluid Ounce (fl oz)'), ('m2', 'Square Meter (m²)'), ('ha', 'Hectare (ha)'), ('ac', 'Acre (ac)'), ('km2', 'Square Kilometer (km²)')], default='kg', max_length=20),
        ),
    ]
