# Generated by Django 5.2 on 2025-04-29 18:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_carddetails_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplacedfinal',
            name='order_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
